### ISSUE TITLE
Add tooltip to legends for graph

### ISSUE THREAD

**Issue by bclarhk** [RedHatInsights/curiosity-frontend#158]
## Description
As a UI/UX person I need to get text for tooltips from pendo doc. As a developer I need to activate legend tooltips, and update copy accordingly.

## Acceptance Criteria
- [x] Graph legend should have tooltips on hover
- [x] Copy should be updated

**Comment by jeperry** [comment]
Latest tooltip text - please have Dan sign off since some of this is modified or inferred from what is in the tour.

**RHEL**
Physical RHEL tip text: `Measured by CPU socket pairs. Each system contributes its installed socket count, rounded upwards to the next even number. `

Virtualized RHEL tip text: `Measured either by the installed socket count of each guest, or where host-guest mappings are required (virtual datacenter subscriptions), the socket count of the hypervisor host is counted, using the same method as physical RHEL.`

Threshold tip text: `A sum of similar subscriptions across all of your contracts`

**OpenShift**
Cores tip text: `Each cluster contributes its core count.`

Threshold tip text: `A sum of similar subscriptions across all of your contracts`

**Comment by rblackbu** [comment]
@cdcabrera approved copy points to pull from for tooltips: 
https://docs.google.com/document/d/1inwEw61AOoSuQCg8pKpxJFxcFWtatWV46pkYJ7vL2j4/edit?ts=5ee12a9f#heading=h.p1p5fk9j641p
