### ISSUE TITLE
[Regression] Could not read long y-axis labels

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#317]
## Description
When y-axis values are much larger (when capacity is 20-30k), user could not read them properly.

### Expected behavior
Large values should not broke UI (see screenshot).

#### Steps to reproduce
1. Have account where capacity is 20k.
2. Visit swatch UI https://ci.cloud.redhat.com/beta/subscriptions/openshift-sw.

### Additional context, version info

Looks like regression from #315 

![Screenshot from 2020-06-16 14-03-07](https://user-images.githubusercontent.com/16951913/84752283-2e6fd100-afdb-11ea-9a52-2dcf8533366a.png)

**Comment by cdcabrera** [comment]
@ntkathole change is merged, confirmation when you're ready. We had to make an educated guess as to why this issue pops up. 

So this first change we are... guessing it has to do with the "default locale". We're not clear on if it's being set in the automated test environment, where the checks are happening. Therefore we've applied the default locale for the GUI as a fallback. 

If this works we'll look at applying the active local in a subsequent issue/pr. **If #319 does not work we need additional information** such as 
- Browser type and version
- User
- And if this is also happening for the RHEL product? 
   - This is important because there is no specific distinction, aside from the route between RHEL and OpenShift, the underlying graph display and logic are the same.

**Comment by ntkathole** [comment]
> @ntkathole change is merged, confirmation when you're ready.

@cdcabrera Issue is not fixed yet.

> 
> If this works we'll look at applying the Platform's active locale in a subsequent issue/pr. **If #319 does not work we need additional information** such as
> 
>     * Browser type and version
>       
>       * The ["can i use" for NumberFormat](https://caniuse.com/#search=NumberFormat)

Browser : Firefox
version: 68.8.0esr (64-bit)

**I also noticed that this issue is not reproducible on chrome (Version 81.0.4044.92 (Official Build) (64-bit))** 

> 
>     * Related/equivalent user credentials

Sent on slack.

> 
>     * And if this is also happening for the RHEL product?
>       
>       * This is important because there is no specific distinction, aside from the route between RHEL and OpenShift, the underlying graph display and logic are the same. This would help refine our tracking

This is happening for both rhel and openshift product.

**Comment by cdcabrera** [comment]
@ntkathole another update has merged, confirmation when you're ready.

**Comment by ntkathole** [comment]
Thanks @cdcabrera New changes resolved the issue. Just a confirmation on if following screenshot showing expected values ? As per new changes are we expecting 0.5K or 500 ?

![Screenshot from 2020-06-18 09-20-52](https://user-images.githubusercontent.com/16951913/85005199-16808480-b176-11ea-8eb9-268145928fe3.png)

We can close this issue if above values are expected.

**Comment by cdcabrera** [comment]
correct @ntkathole we are not expecting `0.5K`, and yup those do appear to be the expected values. 

we did add in a unit test snapshot to confirm so in the future we can at least be warned. those test results are here
- https://github.com/RedHatInsights/curiosity-frontend/blob/ci/src/components/graphCard/__tests__/__snapshots__/graphCardHelpers.test.js.snap#L125-L499

And the start of this, the package that caused the issue Numbro generated a `0.5K`. A related issue is found here
- https://github.com/BenjaminVanRyseghem/numbro/issues/554
