### ISSUE TITLE
CCS copy review

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#46]
## Description
As an end user I'd like to be able to clearly understand the concepts being displayed

## Acceptance Criteria
- [ ] Generate CCS tasks for copy updates

## Assumptions and Questions
- Coordination task
- CCS availability

**Comment by cdcabrera** [comment]
20190918 Quick review @jlprevatt 

1. Granularity tooltips "on" vs "in" vs "for" as related to daily, weekly, monthly, and quarterly copy.
2. Unit name follows granularity type (i.e. daily, weekly, monthly, quarterly)

### Possible quick solutions
- Use "for" for all the granularity types within the tooltip instead of the word "on" 
- "week of" prefix copy and/or "quarter" suffix copy for the tooltips granularity types

<img width="726" alt="Screen Shot 2019-09-18 at 5 24 48 PM" src="https://user-images.githubusercontent.com/3761375/65187212-5d035000-da39-11e9-926a-c4d0a72fe982.png">

**Comment by jlprevatt** [comment]
For 1: The "on" only works for daily, but "for" works in all 4 cases, instead of swapping "on" and "in."
For 2: Other possibilities for quarter include 1Q, 2Q, or 1st quarter, 2nd quarter, etc. But "Q" could be more problematic for any future localization. "1st quarter" and etc. might require a docs line somewhere that says "...quarterly based on calendar quarters..."

**Comment by cdcabrera** [comment]
Closing, reopen accordingly
