### ISSUE TITLE
Rename satellite/capsule request calls as per api 

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#553]
## Description
As per https://issues.redhat.com/browse/ENT-3409, api changed satellite/capsule product names.

![Screenshot from 2021-01-18 11-51-26](https://user-images.githubusercontent.com/16951913/104879292-93314680-5983-11eb-96a6-97ed6554f275.png)

### Expected behavior
Correct api calling for satellite/capsule pages.

#### Steps to reproduce
1. https://ci.cloud.redhat.com/beta/subscriptions/satellite-sw/all 

### Additional context, version info
![Screenshot from 2021-01-18 09-46-23](https://user-images.githubusercontent.com/16951913/104879309-9e847200-5983-11eb-9725-02d5b8475df8.png)

**Comment by cdcabrera** [comment]
Relates #542 #541

**Comment by cdcabrera** [comment]
@ntkathole we'll let you handle closing this issue down the new routes follow a similar structure to RHEL and the related architectures. We were informed by UX/design that a unique Capsule route may not be thing in the future since they're still working through the Satellite view design

the routes are
   - `Satellite` = `/subscriptions/satellite-sw/all`
      -`Satellite Capsule` = `/subscriptions/satellite-sw/satellite-capsule` 
      -`Satellite Server` = `/subscriptions/satellite-sw/satellite-server`

**Comment by ntkathole** [comment]
Fixed!
