### ISSUE TITLE
Not able to reset display name filtering without page refresh

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#559]
## Description
Once user search something with "filter by display name", user is not able to clear that filter (or have to refresh the page).

Also it would be great, if we can make that box as "**search-as-you-type**" similar to what we have on inventory page (https://ci.cloud.redhat.com/beta/insights/inventory)

### Expected behavior
When nothing typed in "filter by display name" and press enter or hit search button, all hosts from system table should display.

#### Steps to reproduce
1. Navigate to ci-beta environemnt
2. Search something in system table
3. Try to see all hosts in system table without page refresh.

### Additional context, version info
![filter-display-2021-01-22_14 35 45](https://user-images.githubusercontent.com/16951913/105470376-7c5e5d00-5cbf-11eb-8d25-f5172c15dfa1.gif)

**Comment by cdcabrera** [comment]
1. So just to confirm, looks like you're using Firefox, yes?
   - Clearing a blank field we can look at doing that since Firefox appears to have issues showing this part of the field you're looking at correct? <img width="262" alt="Screen Shot 2021-01-22 at 10 18 01 AM" src="https://user-images.githubusercontent.com/3761375/105509128-32fc1680-5c9b-11eb-9cf8-7046781ff25e.png">

2. Type-as-you-go is off the table, hammering the api first round needs to be brought up with the api team. This can be approached incrementally

**Comment by cdcabrera** [comment]
@ntkathole change should be in QA/CI-beta ready for confirmation

**Comment by ntkathole** [comment]
Fixed!
